package com.bank.model;

import com.bank.enums.AlertSeverity;
import com.bank.enums.AlertStatus;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Represents a security or fraud alert generated by the system rules.
 * Implements Encapsulation and Serialization.
 */
public class SecurityAlert implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;
    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final String alertId;
    private final String customerId;
    private final String accountId;
    private final AlertSeverity severity;
    private AlertStatus status;
    private final String ruleTriggered;
    private final String description;
    private final LocalDateTime timestamp;
    private String resolutionNotes;

    public SecurityAlert() {
        this("", null, null, AlertSeverity.LOW, "GENERAL", "Initial alert");
    }

    public SecurityAlert(String alertId, String customerId, String accountId,
                         AlertSeverity severity, String ruleTriggered, String description) {
        this(alertId, customerId, accountId, severity, AlertStatus.OPEN, ruleTriggered, description, LocalDateTime.now(), null);
    }

    public SecurityAlert(String alertId, String customerId, String accountId,
                         AlertSeverity severity, AlertStatus status, String ruleTriggered,
                         String description, LocalDateTime timestamp, String resolutionNotes) {
        this.alertId = alertId;
        this.customerId = customerId;
        this.accountId = accountId;
        this.severity = severity;
        this.status = status;
        this.ruleTriggered = ruleTriggered;
        this.description = description;
        this.timestamp = timestamp != null ? timestamp : LocalDateTime.now();
        this.resolutionNotes = resolutionNotes;
    }

    public void resolve(String resolutionNotes) {
        this.status = AlertStatus.RESOLVED;
        this.resolutionNotes = resolutionNotes;
    }

    public void investigate() {
        this.status = AlertStatus.INVESTIGATING;
    }

    public void dismiss(String reason) {
        this.status = AlertStatus.DISMISSED;
        this.resolutionNotes = reason;
    }

    public String getAlertId() {
        return alertId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public String getAccountId() {
        return accountId;
    }

    public AlertSeverity getSeverity() {
        return severity;
    }

    public AlertStatus getStatus() {
        return status;
    }

    public String getRuleTriggered() {
        return ruleTriggered;
    }

    public String getDescription() {
        return description;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public String getResolutionNotes() {
        return resolutionNotes;
    }

    public String getFormattedTimestamp() {
        return timestamp.format(FORMATTER);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SecurityAlert that)) return false;
        return Objects.equals(alertId, that.alertId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(alertId);
    }

    @Override
    public String toString() {
        return String.format("[%s] ALERT %s | Severity: %s | Status: %s | Rule: %s | Description: %s",
                getFormattedTimestamp(), alertId, severity, status, ruleTriggered, description);
    }
}
